package cp317;

import java.util.Date;

/**
 * Class for Tasks
 * 
 * @author Paris Ngow
 * @version 1.0
 * @since 2020-12-05
 *
 */
public class Task {
	private int id; // unique event ID generated by database
	private String name; // name of event
	private String type; // event type (task/course event)

	/**
	 * Constructor for tasks.
	 * 
	 * @param id,   int
	 * @param name, String
	 * @param type, String
	 */
	public Task(int id, String name, String type) {
		// set event id
		this.id = id;
		// set event name
		this.name = name;
		// set event type
		this.type = type;
	}

	/**
	 * Getter for ID. Returns int.
	 * 
	 * @return id
	 */
	public int getID() {
		return id;
	}

	/**
	 * Getter for name. Returns String.
	 * 
	 * @return name
	 */
	public String getName() {
		return name;
	}

	/**
	 * Getter for event type. Returns String.
	 * 
	 * @return type
	 */
	public String getType() {
		return type;
	}

	/**
	 * Setter for id.
	 * 
	 * @param id, int
	 */
	public void setID(int id) {
		this.id = id;
	}

	/**
	 * Setter for name.
	 * 
	 * @param name, String
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Setter for event type. Either "T" or "C.
	 * 
	 * @param type, String
	 */
	public void setType(String type) {
		this.type = type;
	}

}
